Repository AY2021S1-CS2103-W14-4/tp, pull requests merged in 2020-11, with the labels that each got.

#212 Fix ct/pw and ct/ps incorrectly adding a warehouse
  src/main/java/seedu/clinic/logic/parser/AddCommandParser.java
Labels: type.BugFix

#226 Fix AddCommand not throwing error
  src/main/java/seedu/clinic/logic/commands/AddCommand.java
  src/main/java/seedu/clinic/logic/parser/AddCommandParser.java
Labels: type.BugFix

#228 Add autocomplete documentation
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/jeffreytjs.md
  src/main/java/seedu/clinic/ui/AutoCompleteTextField.java
Labels: documentation

#234 Update UML Diagrams and formatting for AddCommand
  docs/DeveloperGuide.md
  docs/diagrams/AddCommandActivityDiagram.puml
  docs/diagrams/AddCommandSequenceDiagram.puml
  docs/diagrams/AddCommandSequenceDiagramSimplified.puml
  docs/images/AddCommandActivityDiagram.png
  docs/images/AddCommandSequenceDiagram.png
Labels: documentation

#231 Initial code housekeeping
  docs/index.md
  src/main/java/seedu/clinic/logic/commands/AddCommand.java
  src/main/java/seedu/clinic/logic/commands/ClearCommand.java
  src/main/java/seedu/clinic/logic/commands/DeleteCommand.java
  src/main/java/seedu/clinic/logic/commands/EditCommand.java
  src/main/java/seedu/clinic/logic/commands/ExitCommand.java
  src/main/java/seedu/clinic/logic/commands/HelpCommand.java
  src/main/java/seedu/clinic/logic/parser/AddCommandParser.java
  src/main/java/seedu/clinic/logic/parser/AssignMacroCommandParser.java
  src/main/java/seedu/clinic/logic/parser/ClinicParser.java
  src/main/java/seedu/clinic/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/clinic/logic/parser/EditCommandParser.java
  src/main/java/seedu/clinic/logic/parser/FindCommandParser.java
  src/main/java/seedu/clinic/logic/parser/ParserUtil.java
  src/main/java/seedu/clinic/logic/parser/RemoveMacroCommandParser.java
  src/main/java/seedu/clinic/logic/parser/UpdateCommandParser.java
  src/main/java/seedu/clinic/logic/parser/ViewCommandParser.java
  src/main/java/seedu/clinic/model/Model.java
  src/main/java/seedu/clinic/model/ModelManager.java
  src/main/java/seedu/clinic/model/attribute/Phone.java
  src/main/java/seedu/clinic/model/attribute/Remark.java
  src/main/java/seedu/clinic/model/macro/Alias.java
  src/main/java/seedu/clinic/model/product/Product.java
  src/main/java/seedu/clinic/ui/WarehouseCard.java
Labels: type.Task

#232 Updated DG with relevant testcases
  docs/DeveloperGuide.md
  docs/SettingUp.md
  docs/UserGuide.md
  docs/diagrams/EditCommandActivityDiagram.puml
  docs/diagrams/EditCommandClassDiagram.puml
  docs/diagrams/EditCommandSequenceDiagram.puml
  docs/diagrams/EditCommandSequenceTokenizing.puml
  docs/diagrams/EditDescriptorClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/ViewCommandActivity.puml
  docs/diagrams/ViewCommandSequenceDiagram.puml
  docs/images/EditCommandActivityDiagram.png
  docs/images/EditCommandClassDiagram.png
  docs/images/EditCommandDescriptorWarehouseDetailsSequenceDiagram.png
  docs/images/EditCommandSequenceDiagram.png
  docs/images/EditCommandSequenceTokenizing.png
  docs/images/EditDescriptorClassDiagram.png
  docs/images/HelpCommandActivityDiagram.png
  docs/images/UiClassDiagram.png
  docs/images/ViewCommandActivity.png
  docs/images/ViewCommandSequenceDiagram.png
  src/main/java/seedu/clinic/logic/commands/EditCommand.java
  src/main/java/seedu/clinic/logic/commands/FindCommand.java
  src/main/java/seedu/clinic/logic/commands/RemoveMacroCommand.java
  src/main/java/seedu/clinic/model/CommandHistoryList.java
Labels: documentation

#237 Fix internal test bugs
  src/main/java/seedu/clinic/model/attribute/Email.java
  src/main/java/seedu/clinic/ui/AutoCompleteTextField.java
  src/main/java/seedu/clinic/ui/SupplierCard.java
  src/main/java/seedu/clinic/ui/WarehouseCard.java
  src/test/java/seedu/clinic/model/attribute/EmailTest.java
Labels: type.BugFix

#241 Fix product tags overflowing
  src/main/java/seedu/clinic/ui/SupplierCard.java
  src/main/java/seedu/clinic/ui/WarehouseCard.java
  src/main/resources/view/SupplierListCard.fxml
  src/main/resources/view/WarehouseListCard.fxml
Labels: type.BugFix

#247 Update DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/AddCommandClassDiagram.puml
  docs/images/AddCommandClassDiagram.png
  docs/images/BetterModelClassDiagram.png
  docs/images/DeleteCommandActivityDiagram.png
  docs/images/DeleteCommandSequenceDiagram.png
  docs/images/DeleteCommandSequenceDiagram2.png
  docs/images/UiClassDiagram.png
Labels: documentation
